In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

Reading dataset :

In [2]:
df = pd.read_csv('Affairs.csv')
df.head()

,Unnamed: 0,naffairs,kids,vryunhap,unhap,avgmarr,hapavg,vryhap,antirel,notrel,slghtrel,smerel,vryrel,yrsmarr1,yrsmarr2,yrsmarr3,yrsmarr4,yrsmarr5,yrsmarr6
0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0
1,2,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0
2,3,3,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0
3,4,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1
4,5,3,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0

Lookind for last 5 records :

In [3]:
df.tail()

,Unnamed: 0,naffairs,kids,vryunhap,unhap,avgmarr,hapavg,vryhap,antirel,notrel,slghtrel,smerel,vryrel,yrsmarr1,yrsmarr2,yrsmarr3,yrsmarr4,yrsmarr5,yrsmarr6
596,597,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
597,598,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1
598,599,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
599,600,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1
600,601,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0

In [4]:
df.columns

Index(['Unnamed: 0', 'naffairs', 'kids', 'vryunhap', 'unhap', 'avgmarr',
       'hapavg', 'vryhap', 'antirel', 'notrel', 'slghtrel', 'smerel', 'vryrel',
       'yrsmarr1', 'yrsmarr2', 'yrsmarr3', 'yrsmarr4', 'yrsmarr5', 'yrsmarr6'],
      dtype='object')

Dropping Unneccesary Columns :

In [5]:
df.drop('Unnamed: 0', axis = 'columns', inplace = True)

Checking for null values :

In [6]:
df.isna().sum()

naffairs    0
kids        0
vryunhap    0
unhap       0
avgmarr     0
hapavg      0
vryhap      0
antirel     0
notrel      0
slghtrel    0
smerel      0
vryrel      0
yrsmarr1    0
yrsmarr2    0
yrsmarr3    0
yrsmarr4    0
yrsmarr5    0
yrsmarr6    0
dtype: int64

No null values in any column of the dataset

In [7]:
df.describe()

,naffairs,kids,vryunhap,unhap,avgmarr,hapavg,vryhap,antirel,notrel,slghtrel,smerel,vryrel,yrsmarr1,yrsmarr2,yrsmarr3,yrsmarr4,yrsmarr5,yrsmarr6
count,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000
mean,1.455907,0.715474,0.026622,0.109817,0.154742,0.322795,0.386023,0.079867,0.272879,0.214642,0.316140,0.116473,0.086522,0.146423,0.174709,0.136439,0.116473,0.339434
std,3.298758,0.451564,0.161111,0.312922,0.361960,0.467935,0.487242,0.271313,0.445810,0.410916,0.465355,0.321058,0.281368,0.353824,0.380034,0.343540,0.321058,0.473912
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
max,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   naffairs  601 non-null    int64
 1   kids      601 non-null    int64
 2   vryunhap  601 non-null    int64
 3   unhap     601 non-null    int64
 4   avgmarr   601 non-null    int64
 5   hapavg    601 non-null    int64
 6   vryhap    601 non-null    int64
 7   antirel   601 non-null    int64
 8   notrel    601 non-null    int64
 9   slghtrel  601 non-null    int64
 10  smerel    601 non-null    int64
 11  vryrel    601 non-null    int64
 12  yrsmarr1  601 non-null    int64
 13  yrsmarr2  601 non-null    int64
 14  yrsmarr3  601 non-null    int64
 15  yrsmarr4  601 non-null    int64
 16  yrsmarr5  601 non-null    int64
 17  yrsmarr6  601 non-null    int64
dtypes: int64(18)
memory usage: 84.6 KB

Data type of all columns is integer

In [9]:
df['naffairs'].mean()

1.4559068219633944

In [10]:
df.head()

,naffairs,kids,vryunhap,unhap,avgmarr,hapavg,vryhap,antirel,notrel,slghtrel,smerel,vryrel,yrsmarr1,yrsmarr2,yrsmarr3,yrsmarr4,yrsmarr5,yrsmarr6
0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0
2,3,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0
3,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1
4,3,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0

In [11]:
threshold = 1.45
df['naffairs'] = (df['naffairs'] > threshold).astype(int)

In [12]:
# for i in range(len(df['naffairs'])):
#     if df['naffairs'][i] < threshold:
#         df['naffairs'][i] = 0
#     else :
#         df['naffairs'][i] = 1

In [13]:
df

,naffairs,kids,vryunhap,unhap,avgmarr,hapavg,vryhap,antirel,notrel,slghtrel,smerel,vryrel,yrsmarr1,yrsmarr2,yrsmarr3,yrsmarr4,yrsmarr5,yrsmarr6
0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0
2,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0
3,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1
4,1,1,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
597,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1
598,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
599,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1
600,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0

In [17]:
input = df.drop('naffairs', axis = 'columns')
target = df['naffairs']

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score

In [23]:
X_train, X_test, y_train, y_test = train_test_split(input, target, test_size=0.2)

In [24]:
model = LogisticRegression()

In [31]:
parameter = {'penalty':['l2','elasticnet'], 'C':[1,2,3,4,5,6,7,8,9,10,20,40,60,80,100], 'max_iter':[100,200,300,400,500,600,700,800,900]}

In [32]:
classifier = GridSearchCV(model, param_grid=parameter, scoring='accuracy', cv=5)

In [33]:
classifier.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 40, 60, 80,
                               100],
                         'max_iter': [100, 200, 300, 400, 500, 600, 700, 800,
                                      900],
                         'penalty': ['l2', 'elasticnet']},
             scoring='accuracy')

In [35]:
classifier.best_score_

0.8041666666666668

In [36]:
pred = classifier.predict(X_test)

In [40]:
accuracy_score(pred, y_test)

0.8347107438016529

In [42]:
report = classification_report(pred, y_test)
print(report)

              precision    recall  f1-score   support

           0       0.98      0.84      0.91       115
           1       0.18      0.67      0.29         6

    accuracy                           0.83       121
   macro avg       0.58      0.76      0.60       121
weighted avg       0.94      0.83      0.88       121

In [43]:
model.fit(X_train, y_train)

LogisticRegression()

In [44]:
pd = model.predict(X_test)

In [45]:
accuracy_score(pd, y_test)

0.8347107438016529